# Travis (https://travis-ci.org) configuration file

language: generic
matrix:
    include:
        - os: linux
          env: TRAVIS_PYTHON_VERSION=2.7
#          script:
#            # listing everything in howto folder recursively
#            - ls -alR ./howto/
#            # setting flag: don't proceed if one of commands fails.
#            - set -e
#            # creating folder for tests (travis doesn't allow this).
#            - mkdir -p ./.cache/rep
#            # testing all but notebooks
#            - nosetests -v --detailed-errors --nocapture ./tests/test_*
#            # testing only notebooks
#            - nosetests -v --detailed-errors --nocapture --stop ./tests/z_test_*
#            # if on master and tests passed successfully, trigger rebuilding of docker image.
#            - if [[ "$TRAVIS_BRANCH" = "master" && "${TRAVIS_PYTHON_VERSION:0:1}" = "2" ]] ; then make push-latest ; fi
#            # reseting flag
#            - set +e
#        - os: linux
#          env: TRAVIS_PYTHON_VERSION=3.5
        - os: osx
          env: TRAVIS_PYTHON_VERSION=2.7
#        - os: osx
#          env: TRAVIS_PYTHON_VERSION=3.5

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew install homebrew/science/root;
      source $(brew --prefix root)/libexec/thisroot.sh;
      which pip
    else
      source ci/install_repbase.sh;
      conda list;
    fi
  # printing DEBUG information
  - which python
  - echo $LD_LIBRARY_PATH
install:
  - pip install .
script:
  # creating folder for tests (travis doesn't allow this).
  - mkdir -p ./.cache/rep
  # testing all but notebooks
  - nosetests -v --detailed-errors --nocapture ./tests/test_*
notifications:
  email: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4eb609958a03b4bc1df5
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
