language: python
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libffi-dev
    - wget
    - gfortran
    - libxft-dev
    - libxpm-dev
python:
  - "2.7"
  - "3.4"
before_install:
  - travis_retry ci/install-conda-env.sh
install:
  - travis_retry pip install .
script:
  - nosetests tests
  #- nosetests -vd tests/z_test_notebook.py
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano