language: python
sudo: true
# addons:
#   apt:
#     packages:
#     - build-essential
#     - libatlas-dev
#     - libatlas-base-dev
#     - liblapack-dev
#     - libffi-dev
#     - wget
#     - gfortran
#     - libxft-dev
#     - libxpm-dev
python:
  - "2.7"
  - "3.4"
before_install:
  - source ci/install-conda-env.sh
# DEBUG
  - which python
  - conda list
  - echo $LD_LIBRARY_PATH
install:
  - pip install .
script:
  # - nosetests tests
  - nosetests -vd tests/z_test_notebook.py
cache:
  - apt: true
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
branches:
  - only:
    - develop
notifications:
  - email: false