language: python
sudo: true
python:
  - "2.7"
  - "3.4"
before_install:
  - source ci/install-conda-env.sh
# DEBUG
  - which python
  - conda list
  - echo $LD_LIBRARY_PATH
install:
  - pip install .
script:
#  - nosetests tests
  - nosetests --verbosity=10 -d tests/z_test_notebook.py
cache:
  - apt: true
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
branches:
  - only:
    - develop
    - master
notifications:
  - email: false
