language: python
sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - build-essential
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libffi-dev
    - wget
    - gfortran
    - libxft-dev
    - libxpm-dev
python:
  - "2.7"
  - "3.4"
before_install:
  - set -x
  - source ci/install-repbase-env.sh
# DEBUG
  - which python
  - conda list
  - echo $LD_LIBRARY_PATH
install:
  - pip install .
script:
  - nosetests --nocapture -vd tests | grep -v "downhill.base:232" ; test ${PIPESTATUS[0]} -eq 0
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "${TRAVIS_PYTHON_VERSION:0:1}" == "2" ]] ; then make push-latest ; fi
cache:
  - apt: true
  - directories:
    - $HOME/.theano
#    - $HOME/.cache/pip
#    - $HOME/miniconda/pkgs
branches:
  - only:
    - develop
    - master
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4eb609958a03b4bc1df5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
