language: python
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libffi-dev
    - wget
    - gfortran
    - libxft-dev
    - libxpm-dev
python:
  - "2.7"
  - "3.4"
install:
  # - ci/install-conda-env.sh
  - conda env update -f ci/environment.yaml
  - which python
  - pip install .
script:
  - nosetests tests
  #- nosetests -vd tests/z_test_notebook.py
cache:
  - apt: true
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
branches:
  - only:
    - develop