language: python
sudo: true
# addons:
#   apt:
#     packages:
#     - build-essential
#     - libatlas-dev
#     - libatlas-base-dev
#     - liblapack-dev
#     - libffi-dev
#     - wget
#     - gfortran
#     - libxft-dev
#     - libxpm-dev
python:
  - "2.7"
  - "3.4"
before_install:
  - source ci/install-repbase-env.sh
# DEBUG
  - which python
  - conda list
  - echo $LD_LIBRARY_PATH
install:
  - pip install .
  - pip install runipy
# DEBUG
  - conda list
  - echo $LD_LIBRARY_PATH
  - ipython -c "import matplotlib"
  - ipython -c "import matplotlib.colorbar"
  - ipython -c "import matplotlib.artist as martist"
script:
#  - nosetests tests
  - nosetests --nocapture -d tests/z_test_notebook.py
cache:
  - apt: true
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
    - $HOME/miniconda/pkgs
branches:
  - only:
    - develop
    - master
notifications:
  - email: false
