language: python
sudo: false
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libffi-dev
    - wget
    - gfortran
python:
  - "2.7"
  - "3.4"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION -c remenska root_numpy
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy six pandas
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION theano scikit-learn
install:
  - travis_retry pip install . --no-dependencies
script: nosetests tests
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano