name: jupyterhub_py3
dependencies:
  - python=3.4
  - ipython-notebook=4.0.4
  - matplotlib=1.4.3
  - numpy=1.10.*
  - pandas=0.17.*
  - scikit-learn=0.16.1
  - scipy=0.16.*
  - six=1.10.0
  - bokeh=0.10
  - pip:
    - neurolab==0.3.5
    - theano==0.7.0
    - theanets==0.6.2
    - pybrain==0.3
    - mpld3==0.2
    - xgboost==0.4a30
    - jupyterhub
